/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { ConfigLpParams, configLpParamsBeet } from '../types/ConfigLpParams.js'

/**
 * @category Instructions
 * @category ConfigLp
 * @category generated
 */
export type ConfigLpInstructionArgs = {
  params: ConfigLpParams
}
/**
 * @category Instructions
 * @category ConfigLp
 * @category generated
 */
export const configLpStruct = new beet.FixableBeetArgsStruct<
  ConfigLpInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', configLpParamsBeet],
  ],
  'ConfigLpInstructionArgs',
)
/**
 * Accounts required by the _configLp_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] adminAuthority
 * @category Instructions
 * @category ConfigLp
 * @category generated
 */
export type ConfigLpInstructionAccounts = {
  state: web3.PublicKey
  adminAuthority: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const configLpInstructionDiscriminator = [
  10, 24, 168, 119, 86, 48, 225, 17,
]

/**
 * Creates a _ConfigLp_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ConfigLp
 * @category generated
 */
export function createConfigLpInstruction(
  accounts: ConfigLpInstructionAccounts,
  args: ConfigLpInstructionArgs,
  programId = new web3.PublicKey('MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD'),
) {
  const [data] = configLpStruct.serialize({
    instructionDiscriminator: configLpInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.adminAuthority,
      isWritable: false,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
