/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ReallocStakeList
 * @category generated
 */
export type ReallocStakeListInstructionArgs = {
  capacity: number
}
/**
 * @category Instructions
 * @category ReallocStakeList
 * @category generated
 */
export const reallocStakeListStruct = new beet.BeetArgsStruct<
  ReallocStakeListInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['capacity', beet.u32],
  ],
  'ReallocStakeListInstructionArgs',
)
/**
 * Accounts required by the _reallocStakeList_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] adminAuthority
 * @property [_writable_] stakeList
 * @property [_writable_, **signer**] rentFunds
 * @category Instructions
 * @category ReallocStakeList
 * @category generated
 */
export type ReallocStakeListInstructionAccounts = {
  state: web3.PublicKey
  adminAuthority: web3.PublicKey
  stakeList: web3.PublicKey
  rentFunds: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const reallocStakeListInstructionDiscriminator = [
  12, 36, 124, 27, 128, 96, 85, 199,
]

/**
 * Creates a _ReallocStakeList_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ReallocStakeList
 * @category generated
 */
export function createReallocStakeListInstruction(
  accounts: ReallocStakeListInstructionAccounts,
  args: ReallocStakeListInstructionArgs,
  programId = new web3.PublicKey('MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD'),
) {
  const [data] = reallocStakeListStruct.serialize({
    instructionDiscriminator: reallocStakeListInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.adminAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.stakeList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.rentFunds,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
