/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category Resume
 * @category generated
 */
export const resumeStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ResumeInstructionArgs',
)
/**
 * Accounts required by the _resume_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] pauseAuthority
 * @category Instructions
 * @category Resume
 * @category generated
 */
export type ResumeInstructionAccounts = {
  state: web3.PublicKey
  pauseAuthority: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const resumeInstructionDiscriminator = [
  1, 166, 51, 170, 127, 32, 141, 206,
]

/**
 * Creates a _Resume_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category Resume
 * @category generated
 */
export function createResumeInstruction(
  accounts: ResumeInstructionAccounts,
  programId = new web3.PublicKey('MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD'),
) {
  const [data] = resumeStruct.serialize({
    instructionDiscriminator: resumeInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.pauseAuthority,
      isWritable: false,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
