/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  AddCollectionExternalPluginAdapterV1Args,
  addCollectionExternalPluginAdapterV1ArgsBeet,
} from '../types/AddCollectionExternalPluginAdapterV1Args.js'

/**
 * @category Instructions
 * @category AddCollectionExternalPluginAdapterV1
 * @category generated
 */
export type AddCollectionExternalPluginAdapterV1InstructionArgs = {
  addCollectionExternalPluginAdapterV1Args: AddCollectionExternalPluginAdapterV1Args
}
/**
 * @category Instructions
 * @category AddCollectionExternalPluginAdapterV1
 * @category generated
 */
export const AddCollectionExternalPluginAdapterV1Struct =
  new beet.FixableBeetArgsStruct<
    AddCollectionExternalPluginAdapterV1InstructionArgs & {
      instructionDiscriminator: number
    }
  >(
    [
      ['instructionDiscriminator', beet.u8],
      [
        'addCollectionExternalPluginAdapterV1Args',
        addCollectionExternalPluginAdapterV1ArgsBeet,
      ],
    ],
    'AddCollectionExternalPluginAdapterV1InstructionArgs',
  )
/**
 * Accounts required by the _AddCollectionExternalPluginAdapterV1_ instruction
 *
 * @property [_writable_] collection
 * @property [_writable_, **signer**] payer
 * @property [**signer**] authority (optional)
 * @property [] logWrapper (optional)
 * @category Instructions
 * @category AddCollectionExternalPluginAdapterV1
 * @category generated
 */
export type AddCollectionExternalPluginAdapterV1InstructionAccounts = {
  collection: web3.PublicKey
  payer: web3.PublicKey
  authority?: web3.PublicKey
  systemProgram?: web3.PublicKey
  logWrapper?: web3.PublicKey
}

export const addCollectionExternalPluginAdapterV1InstructionDiscriminator = 23

/**
 * Creates a _AddCollectionExternalPluginAdapterV1_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddCollectionExternalPluginAdapterV1
 * @category generated
 */
export function createAddCollectionExternalPluginAdapterV1Instruction(
  accounts: AddCollectionExternalPluginAdapterV1InstructionAccounts,
  args: AddCollectionExternalPluginAdapterV1InstructionArgs,
  programId = new web3.PublicKey(
    'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
  ),
) {
  const [data] = AddCollectionExternalPluginAdapterV1Struct.serialize({
    instructionDiscriminator:
      addCollectionExternalPluginAdapterV1InstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.collection,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.authority ?? programId,
      isWritable: false,
      isSigner: accounts.authority != null,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.logWrapper ?? programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
