/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CreateCollectionV2Args,
  createCollectionV2ArgsBeet,
} from '../types/CreateCollectionV2Args.js'

/**
 * @category Instructions
 * @category CreateCollectionV2
 * @category generated
 */
export type CreateCollectionV2InstructionArgs = {
  createCollectionV2Args: CreateCollectionV2Args
}
/**
 * @category Instructions
 * @category CreateCollectionV2
 * @category generated
 */
export const CreateCollectionV2Struct = new beet.FixableBeetArgsStruct<
  CreateCollectionV2InstructionArgs & {
    instructionDiscriminator: number
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['createCollectionV2Args', createCollectionV2ArgsBeet],
  ],
  'CreateCollectionV2InstructionArgs',
)
/**
 * Accounts required by the _CreateCollectionV2_ instruction
 *
 * @property [_writable_, **signer**] collection
 * @property [] updateAuthority (optional)
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category CreateCollectionV2
 * @category generated
 */
export type CreateCollectionV2InstructionAccounts = {
  collection: web3.PublicKey
  updateAuthority?: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
}

export const createCollectionV2InstructionDiscriminator = 21

/**
 * Creates a _CreateCollectionV2_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateCollectionV2
 * @category generated
 */
export function createCreateCollectionV2Instruction(
  accounts: CreateCollectionV2InstructionAccounts,
  args: CreateCollectionV2InstructionArgs,
  programId = new web3.PublicKey(
    'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
  ),
) {
  const [data] = CreateCollectionV2Struct.serialize({
    instructionDiscriminator: createCollectionV2InstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.collection,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.updateAuthority ?? programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
