/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  DecompressV1Args,
  decompressV1ArgsBeet,
} from '../types/DecompressV1Args.js'

/**
 * @category Instructions
 * @category DecompressV1
 * @category generated
 */
export type DecompressV1InstructionArgs = {
  decompressV1Args: DecompressV1Args
}
/**
 * @category Instructions
 * @category DecompressV1
 * @category generated
 */
export const DecompressV1Struct = new beet.FixableBeetArgsStruct<
  DecompressV1InstructionArgs & {
    instructionDiscriminator: number
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['decompressV1Args', decompressV1ArgsBeet],
  ],
  'DecompressV1InstructionArgs',
)
/**
 * Accounts required by the _DecompressV1_ instruction
 *
 * @property [_writable_] asset
 * @property [] collection (optional)
 * @property [_writable_, **signer**] payer
 * @property [**signer**] authority (optional)
 * @property [] logWrapper (optional)
 * @category Instructions
 * @category DecompressV1
 * @category generated
 */
export type DecompressV1InstructionAccounts = {
  asset: web3.PublicKey
  collection?: web3.PublicKey
  payer: web3.PublicKey
  authority?: web3.PublicKey
  systemProgram?: web3.PublicKey
  logWrapper?: web3.PublicKey
}

export const decompressV1InstructionDiscriminator = 18

/**
 * Creates a _DecompressV1_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category DecompressV1
 * @category generated
 */
export function createDecompressV1Instruction(
  accounts: DecompressV1InstructionAccounts,
  args: DecompressV1InstructionArgs,
  programId = new web3.PublicKey(
    'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
  ),
) {
  const [data] = DecompressV1Struct.serialize({
    instructionDiscriminator: decompressV1InstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.asset,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.collection ?? programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.authority ?? programId,
      isWritable: false,
      isSigner: accounts.authority != null,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.logWrapper ?? programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
