/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  RevokePluginAuthorityV1Args,
  revokePluginAuthorityV1ArgsBeet,
} from '../types/RevokePluginAuthorityV1Args.js'

/**
 * @category Instructions
 * @category RevokePluginAuthorityV1
 * @category generated
 */
export type RevokePluginAuthorityV1InstructionArgs = {
  revokePluginAuthorityV1Args: RevokePluginAuthorityV1Args
}
/**
 * @category Instructions
 * @category RevokePluginAuthorityV1
 * @category generated
 */
export const RevokePluginAuthorityV1Struct = new beet.BeetArgsStruct<
  RevokePluginAuthorityV1InstructionArgs & {
    instructionDiscriminator: number
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['revokePluginAuthorityV1Args', revokePluginAuthorityV1ArgsBeet],
  ],
  'RevokePluginAuthorityV1InstructionArgs',
)
/**
 * Accounts required by the _RevokePluginAuthorityV1_ instruction
 *
 * @property [_writable_] asset
 * @property [_writable_] collection (optional)
 * @property [_writable_, **signer**] payer
 * @property [**signer**] authority (optional)
 * @property [] logWrapper (optional)
 * @category Instructions
 * @category RevokePluginAuthorityV1
 * @category generated
 */
export type RevokePluginAuthorityV1InstructionAccounts = {
  asset: web3.PublicKey
  collection?: web3.PublicKey
  payer: web3.PublicKey
  authority?: web3.PublicKey
  systemProgram?: web3.PublicKey
  logWrapper?: web3.PublicKey
}

export const revokePluginAuthorityV1InstructionDiscriminator = 10

/**
 * Creates a _RevokePluginAuthorityV1_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RevokePluginAuthorityV1
 * @category generated
 */
export function createRevokePluginAuthorityV1Instruction(
  accounts: RevokePluginAuthorityV1InstructionAccounts,
  args: RevokePluginAuthorityV1InstructionArgs,
  programId = new web3.PublicKey(
    'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
  ),
) {
  const [data] = RevokePluginAuthorityV1Struct.serialize({
    instructionDiscriminator: revokePluginAuthorityV1InstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.asset,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.collection ?? programId,
      isWritable: accounts.collection != null,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.authority ?? programId,
      isWritable: false,
      isSigner: accounts.authority != null,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.logWrapper ?? programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
