/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  UpdateExternalPluginAdapterV1Args,
  updateExternalPluginAdapterV1ArgsBeet,
} from '../types/UpdateExternalPluginAdapterV1Args.js'

/**
 * @category Instructions
 * @category UpdateExternalPluginAdapterV1
 * @category generated
 */
export type UpdateExternalPluginAdapterV1InstructionArgs = {
  updateExternalPluginAdapterV1Args: UpdateExternalPluginAdapterV1Args
}
/**
 * @category Instructions
 * @category UpdateExternalPluginAdapterV1
 * @category generated
 */
export const UpdateExternalPluginAdapterV1Struct =
  new beet.FixableBeetArgsStruct<
    UpdateExternalPluginAdapterV1InstructionArgs & {
      instructionDiscriminator: number
    }
  >(
    [
      ['instructionDiscriminator', beet.u8],
      [
        'updateExternalPluginAdapterV1Args',
        updateExternalPluginAdapterV1ArgsBeet,
      ],
    ],
    'UpdateExternalPluginAdapterV1InstructionArgs',
  )
/**
 * Accounts required by the _UpdateExternalPluginAdapterV1_ instruction
 *
 * @property [_writable_] asset
 * @property [_writable_] collection (optional)
 * @property [_writable_, **signer**] payer
 * @property [**signer**] authority (optional)
 * @property [] logWrapper (optional)
 * @category Instructions
 * @category UpdateExternalPluginAdapterV1
 * @category generated
 */
export type UpdateExternalPluginAdapterV1InstructionAccounts = {
  asset: web3.PublicKey
  collection?: web3.PublicKey
  payer: web3.PublicKey
  authority?: web3.PublicKey
  systemProgram?: web3.PublicKey
  logWrapper?: web3.PublicKey
}

export const updateExternalPluginAdapterV1InstructionDiscriminator = 26

/**
 * Creates a _UpdateExternalPluginAdapterV1_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateExternalPluginAdapterV1
 * @category generated
 */
export function createUpdateExternalPluginAdapterV1Instruction(
  accounts: UpdateExternalPluginAdapterV1InstructionAccounts,
  args: UpdateExternalPluginAdapterV1InstructionArgs,
  programId = new web3.PublicKey(
    'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
  ),
) {
  const [data] = UpdateExternalPluginAdapterV1Struct.serialize({
    instructionDiscriminator:
      updateExternalPluginAdapterV1InstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.asset,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.collection ?? programId,
      isWritable: accounts.collection != null,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.authority ?? programId,
      isWritable: false,
      isSigner: accounts.authority != null,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.logWrapper ?? programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
