/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  UpdateCollectionPluginV1Args,
  updateCollectionPluginV1ArgsBeet,
} from '../types/UpdateCollectionPluginV1Args.js'

/**
 * @category Instructions
 * @category UpdateCollectionPluginV1
 * @category generated
 */
export type UpdateCollectionPluginV1InstructionArgs = {
  updateCollectionPluginV1Args: UpdateCollectionPluginV1Args
}
/**
 * @category Instructions
 * @category UpdateCollectionPluginV1
 * @category generated
 */
export const UpdateCollectionPluginV1Struct = new beet.FixableBeetArgsStruct<
  UpdateCollectionPluginV1InstructionArgs & {
    instructionDiscriminator: number
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['updateCollectionPluginV1Args', updateCollectionPluginV1ArgsBeet],
  ],
  'UpdateCollectionPluginV1InstructionArgs',
)
/**
 * Accounts required by the _UpdateCollectionPluginV1_ instruction
 *
 * @property [_writable_] collection
 * @property [_writable_, **signer**] payer
 * @property [**signer**] authority (optional)
 * @property [] logWrapper (optional)
 * @category Instructions
 * @category UpdateCollectionPluginV1
 * @category generated
 */
export type UpdateCollectionPluginV1InstructionAccounts = {
  collection: web3.PublicKey
  payer: web3.PublicKey
  authority?: web3.PublicKey
  systemProgram?: web3.PublicKey
  logWrapper?: web3.PublicKey
}

export const updateCollectionPluginV1InstructionDiscriminator = 7

/**
 * Creates a _UpdateCollectionPluginV1_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateCollectionPluginV1
 * @category generated
 */
export function createUpdateCollectionPluginV1Instruction(
  accounts: UpdateCollectionPluginV1InstructionAccounts,
  args: UpdateCollectionPluginV1InstructionArgs,
  programId = new web3.PublicKey(
    'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
  ),
) {
  const [data] = UpdateCollectionPluginV1Struct.serialize({
    instructionDiscriminator: updateCollectionPluginV1InstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.collection,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.authority ?? programId,
      isWritable: false,
      isSigner: accounts.authority != null,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.logWrapper ?? programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
