/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { UpdateV2Args, updateV2ArgsBeet } from '../types/UpdateV2Args.js'

/**
 * @category Instructions
 * @category UpdateV2
 * @category generated
 */
export type UpdateV2InstructionArgs = {
  updateV2Args: UpdateV2Args
}
/**
 * @category Instructions
 * @category UpdateV2
 * @category generated
 */
export const UpdateV2Struct = new beet.FixableBeetArgsStruct<
  UpdateV2InstructionArgs & {
    instructionDiscriminator: number
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['updateV2Args', updateV2ArgsBeet],
  ],
  'UpdateV2InstructionArgs',
)
/**
 * Accounts required by the _UpdateV2_ instruction
 *
 * @property [_writable_] asset
 * @property [_writable_] collection (optional)
 * @property [_writable_, **signer**] payer
 * @property [**signer**] authority (optional)
 * @property [_writable_] newCollection (optional)
 * @property [] logWrapper (optional)
 * @category Instructions
 * @category UpdateV2
 * @category generated
 */
export type UpdateV2InstructionAccounts = {
  asset: web3.PublicKey
  collection?: web3.PublicKey
  payer: web3.PublicKey
  authority?: web3.PublicKey
  newCollection?: web3.PublicKey
  systemProgram?: web3.PublicKey
  logWrapper?: web3.PublicKey
}

export const updateV2InstructionDiscriminator = 30

/**
 * Creates a _UpdateV2_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateV2
 * @category generated
 */
export function createUpdateV2Instruction(
  accounts: UpdateV2InstructionAccounts,
  args: UpdateV2InstructionArgs,
  programId = new web3.PublicKey(
    'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
  ),
) {
  const [data] = UpdateV2Struct.serialize({
    instructionDiscriminator: updateV2InstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.asset,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.collection ?? programId,
      isWritable: accounts.collection != null,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.authority ?? programId,
      isWritable: false,
      isSigner: accounts.authority != null,
    },
    {
      pubkey: accounts.newCollection ?? programId,
      isWritable: accounts.newCollection != null,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.logWrapper ?? programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
