version: '2'

services:
  marinade-finance:
    build: ../..
    volumes:
      - ~/indexer.data:/app/data:rw
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ../../.env
      - ./.env
    environment:
      - INDEXER=marinade-finance
      - LETSENCRYPT_HOST=marinade-finance.api.aleph.cloud
      - VIRTUAL_HOST=marinade-finance.api.aleph.cloud
      - VIRTUAL_PORT=8080
      - SOLANA_RPC=
    network_mode: bridge
