/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  ExternalPluginAdapterInitInfo,
  externalPluginAdapterInitInfoBeet,
} from './ExternalPluginAdapterInitInfo.js'
export type AddCollectionExternalPluginAdapterV1Args = {
  initInfo: ExternalPluginAdapterInitInfo
}

/**
 * @category userTypes
 * @category generated
 */
export const addCollectionExternalPluginAdapterV1ArgsBeet =
  new beet.FixableBeetArgsStruct<AddCollectionExternalPluginAdapterV1Args>(
    [['initInfo', externalPluginAdapterInitInfoBeet]],
    'AddCollectionExternalPluginAdapterV1Args',
  )
