/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { Authority, authorityBeet } from './Authority.js'
import {
  ExternalPluginAdapterSchema,
  externalPluginAdapterSchemaBeet,
} from './ExternalPluginAdapterSchema.js'
export type AppData = {
  dataAuthority: Authority
  schema: ExternalPluginAdapterSchema
}

/**
 * @category userTypes
 * @category generated
 */
export const appDataBeet = new beet.FixableBeetArgsStruct<AppData>(
  [
    ['dataAuthority', authorityBeet],
    ['schema', externalPluginAdapterSchemaBeet],
  ],
  'AppData',
)
