/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { PluginType, pluginTypeBeet } from './PluginType.js'
import { Authority, authorityBeet } from './Authority.js'
export type ApprovePluginAuthorityV1Args = {
  pluginType: PluginType
  newAuthority: Authority
}

/**
 * @category userTypes
 * @category generated
 */
export const approvePluginAuthorityV1ArgsBeet =
  new beet.FixableBeetArgsStruct<ApprovePluginAuthorityV1Args>(
    [
      ['pluginType', pluginTypeBeet],
      ['newAuthority', authorityBeet],
    ],
    'ApprovePluginAuthorityV1Args',
  )
