/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { Attribute, attributeBeet } from './Attribute.js'
export type Attributes = {
  attributeList: Attribute[]
}

/**
 * @category userTypes
 * @category generated
 */
export const attributesBeet = new beet.FixableBeetArgsStruct<Attributes>(
  [['attributeList', beet.array(attributeBeet)]],
  'Attributes',
)
