/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { CompressionProof, compressionProofBeet } from './CompressionProof.js'
export type BurnCollectionV1Args = {
  compressionProof: beet.COption<CompressionProof>
}

/**
 * @category userTypes
 * @category generated
 */
export const burnCollectionV1ArgsBeet =
  new beet.FixableBeetArgsStruct<BurnCollectionV1Args>(
    [['compressionProof', beet.coption(compressionProofBeet)]],
    'BurnCollectionV1Args',
  )
