/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type CompressV1Args = {
  mock: string
}

/**
 * @category userTypes
 * @category generated
 */
export const compressV1ArgsBeet =
  new beet.FixableBeetArgsStruct<CompressV1Args>(
    [['mock', beet.utf8String]],
    'CompressV1Args',
  )
