/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { UpdateAuthority, updateAuthorityBeet } from './UpdateAuthority.js'
import {
  HashablePluginSchema,
  hashablePluginSchemaBeet,
} from './HashablePluginSchema.js'
export type CompressionProof = {
  owner: web3.PublicKey
  updateAuthority: UpdateAuthority
  name: string
  uri: string
  seq: beet.bignum
  plugins: HashablePluginSchema[]
}

/**
 * @category userTypes
 * @category generated
 */
export const compressionProofBeet =
  new beet.FixableBeetArgsStruct<CompressionProof>(
    [
      ['owner', beetSolana.publicKey],
      ['updateAuthority', updateAuthorityBeet],
      ['name', beet.utf8String],
      ['uri', beet.utf8String],
      ['seq', beet.u64],
      ['plugins', beet.array(hashablePluginSchemaBeet)],
    ],
    'CompressionProof',
  )
