/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { DataState, dataStateBeet } from './DataState.js'
import {
  PluginAuthorityPair,
  pluginAuthorityPairBeet,
} from './PluginAuthorityPair.js'
export type CreateV1Args = {
  dataState: DataState
  name: string
  uri: string
  plugins: beet.COption<PluginAuthorityPair[]>
}

/**
 * @category userTypes
 * @category generated
 */
export const createV1ArgsBeet = new beet.FixableBeetArgsStruct<CreateV1Args>(
  [
    ['dataState', dataStateBeet],
    ['name', beet.utf8String],
    ['uri', beet.utf8String],
    ['plugins', beet.coption(beet.array(pluginAuthorityPairBeet))],
  ],
  'CreateV1Args',
)
