/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { LinkedDataKey, linkedDataKeyBeet } from './LinkedDataKey.js'
import {
  ExternalPluginAdapterSchema,
  externalPluginAdapterSchemaBeet,
} from './ExternalPluginAdapterSchema.js'
export type DataSection = {
  parentKey: LinkedDataKey
  schema: ExternalPluginAdapterSchema
}

/**
 * @category userTypes
 * @category generated
 */
export const dataSectionBeet = new beet.FixableBeetArgsStruct<DataSection>(
  [
    ['parentKey', linkedDataKeyBeet],
    ['schema', externalPluginAdapterSchemaBeet],
  ],
  'DataSection',
)
