/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type HashedAssetSchema = {
  assetHash: number[] /* size: 32 */
  pluginHashes: number[] /* size: 32 */[]
}

/**
 * @category userTypes
 * @category generated
 */
export const hashedAssetSchemaBeet =
  new beet.FixableBeetArgsStruct<HashedAssetSchema>(
    [
      ['assetHash', beet.uniformFixedSizeArray(beet.u8, 32)],
      ['pluginHashes', beet.array(beet.uniformFixedSizeArray(beet.u8, 32))],
    ],
    'HashedAssetSchema',
  )
