/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { Authority, authorityBeet } from './Authority.js'
import {
  ExternalPluginAdapterSchema,
  externalPluginAdapterSchemaBeet,
} from './ExternalPluginAdapterSchema.js'
export type LinkedAppDataInitInfo = {
  dataAuthority: Authority
  initPluginAuthority: beet.COption<Authority>
  schema: beet.COption<ExternalPluginAdapterSchema>
}

/**
 * @category userTypes
 * @category generated
 */
export const linkedAppDataInitInfoBeet =
  new beet.FixableBeetArgsStruct<LinkedAppDataInitInfo>(
    [
      ['dataAuthority', authorityBeet],
      ['initPluginAuthority', beet.coption(authorityBeet)],
      ['schema', beet.coption(externalPluginAdapterSchemaBeet)],
    ],
    'LinkedAppDataInitInfo',
  )
