/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { ExtraAccount, extraAccountBeet } from './ExtraAccount.js'
import {
  ValidationResultsOffset,
  validationResultsOffsetBeet,
} from './ValidationResultsOffset.js'
export type Oracle = {
  baseAddress: web3.PublicKey
  baseAddressConfig: beet.COption<ExtraAccount>
  resultsOffset: ValidationResultsOffset
}

/**
 * @category userTypes
 * @category generated
 */
export const oracleBeet = new beet.FixableBeetArgsStruct<Oracle>(
  [
    ['baseAddress', beetSolana.publicKey],
    ['baseAddressConfig', beet.coption(extraAccountBeet)],
    ['resultsOffset', validationResultsOffsetBeet],
  ],
  'Oracle',
)
