/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  HookableLifecycleEvent,
  hookableLifecycleEventBeet,
} from './HookableLifecycleEvent.js'
import {
  ExternalCheckResult,
  externalCheckResultBeet,
} from './ExternalCheckResult.js'
import { ExtraAccount, extraAccountBeet } from './ExtraAccount.js'
import {
  ValidationResultsOffset,
  validationResultsOffsetBeet,
} from './ValidationResultsOffset.js'
export type OracleUpdateInfo = {
  lifecycleChecks: beet.COption<[HookableLifecycleEvent, ExternalCheckResult][]>
  baseAddressConfig: beet.COption<ExtraAccount>
  resultsOffset: beet.COption<ValidationResultsOffset>
}

/**
 * @category userTypes
 * @category generated
 */
export const oracleUpdateInfoBeet =
  new beet.FixableBeetArgsStruct<OracleUpdateInfo>(
    [
      [
        'lifecycleChecks',
        beet.coption(
          beet.array(
            beet.fixedSizeTuple([
              hookableLifecycleEventBeet,
              externalCheckResultBeet,
            ]),
          ),
        ),
      ],
      ['baseAddressConfig', beet.coption(extraAccountBeet)],
      ['resultsOffset', beet.coption(validationResultsOffsetBeet)],
    ],
    'OracleUpdateInfo',
  )
