/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { Plugin, pluginBeet } from './Plugin.js'
import { Authority, authorityBeet } from './Authority.js'
export type PluginAuthorityPair = {
  plugin: Plugin
  authority: beet.COption<Authority>
}

/**
 * @category userTypes
 * @category generated
 */
export const pluginAuthorityPairBeet =
  new beet.FixableBeetArgsStruct<PluginAuthorityPair>(
    [
      ['plugin', pluginBeet],
      ['authority', beet.coption(authorityBeet)],
    ],
    'PluginAuthorityPair',
  )
