/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  ExternalPluginAdapterKey,
  externalPluginAdapterKeyBeet,
} from './ExternalPluginAdapterKey.js'
export type RemoveCollectionExternalPluginAdapterV1Args = {
  key: ExternalPluginAdapterKey
}

/**
 * @category userTypes
 * @category generated
 */
export const removeCollectionExternalPluginAdapterV1ArgsBeet =
  new beet.FixableBeetArgsStruct<RemoveCollectionExternalPluginAdapterV1Args>(
    [['key', externalPluginAdapterKeyBeet]],
    'RemoveCollectionExternalPluginAdapterV1Args',
  )
