/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type UpdateCollectionV1Args = {
  newName: beet.COption<string>
  newUri: beet.COption<string>
}

/**
 * @category userTypes
 * @category generated
 */
export const updateCollectionV1ArgsBeet =
  new beet.FixableBeetArgsStruct<UpdateCollectionV1Args>(
    [
      ['newName', beet.coption(beet.utf8String)],
      ['newUri', beet.coption(beet.utf8String)],
    ],
    'UpdateCollectionV1Args',
  )
