/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  ExternalPluginAdapterKey,
  externalPluginAdapterKeyBeet,
} from './ExternalPluginAdapterKey.js'
import {
  ExternalPluginAdapterUpdateInfo,
  externalPluginAdapterUpdateInfoBeet,
} from './ExternalPluginAdapterUpdateInfo.js'
export type UpdateCollectionExternalPluginAdapterV1Args = {
  key: ExternalPluginAdapterKey
  updateInfo: ExternalPluginAdapterUpdateInfo
}

/**
 * @category userTypes
 * @category generated
 */
export const updateCollectionExternalPluginAdapterV1ArgsBeet =
  new beet.FixableBeetArgsStruct<UpdateCollectionExternalPluginAdapterV1Args>(
    [
      ['key', externalPluginAdapterKeyBeet],
      ['updateInfo', externalPluginAdapterUpdateInfoBeet],
    ],
    'UpdateCollectionExternalPluginAdapterV1Args',
  )
