/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type InitProductParams = {
  firstId: number[] /* size: 32 */
  secondId: number[] /* size: 32 */
  productPrice: beet.bignum
  productMintBump: number
}

/**
 * @category userTypes
 * @category generated
 */
export const initProductParamsBeet = new beet.BeetArgsStruct<InitProductParams>(
  [
    ['firstId', beet.uniformFixedSizeArray(beet.u8, 32)],
    ['secondId', beet.uniformFixedSizeArray(beet.u8, 32)],
    ['productPrice', beet.u64],
    ['productMintBump', beet.u8],
  ],
  'InitProductParams',
)
