/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { PaymentFeePayer, paymentFeePayerBeet } from './PaymentFeePayer.js'
export type InitMarketplaceParams = {
  fee: number
  feeReduction: number
  sellerReward: number
  buyerReward: number
  useCnfts: boolean
  deliverToken: boolean
  transferable: boolean
  chainCounter: boolean
  permissionless: boolean
  rewardsEnabled: boolean
  accessMintBump: number
  feePayer: PaymentFeePayer
}

/**
 * @category userTypes
 * @category generated
 */
export const initMarketplaceParamsBeet =
  new beet.BeetArgsStruct<InitMarketplaceParams>(
    [
      ['fee', beet.u16],
      ['feeReduction', beet.u16],
      ['sellerReward', beet.u16],
      ['buyerReward', beet.u16],
      ['useCnfts', beet.bool],
      ['deliverToken', beet.bool],
      ['transferable', beet.bool],
      ['chainCounter', beet.bool],
      ['permissionless', beet.bool],
      ['rewardsEnabled', beet.bool],
      ['accessMintBump', beet.u8],
      ['feePayer', paymentFeePayerBeet],
    ],
    'InitMarketplaceParams',
  )
