/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type RewardBumps = {
  bump: number
  vaultBumps: Uint8Array
}

/**
 * @category userTypes
 * @category generated
 */
export const rewardBumpsBeet = new beet.FixableBeetArgsStruct<RewardBumps>(
  [
    ['bump', beet.u8],
    ['vaultBumps', beet.bytes],
  ],
  'RewardBumps',
)
