/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type SellerConfig = {
  paymentMint: web3.PublicKey
  productPrice: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const sellerConfigBeet = new beet.BeetArgsStruct<SellerConfig>(
  [
    ['paymentMint', beetSolana.publicKey],
    ['productPrice', beet.u64],
  ],
  'SellerConfig',
)
