/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type TokenConfig = {
  useCnfts: boolean
  deliverToken: boolean
  transferable: boolean
  chainCounter: boolean
}

/**
 * @category userTypes
 * @category generated
 */
export const tokenConfigBeet = new beet.BeetArgsStruct<TokenConfig>(
  [
    ['useCnfts', beet.bool],
    ['deliverToken', beet.bool],
    ['transferable', beet.bool],
    ['chainCounter', beet.bool],
  ],
  'TokenConfig',
)
