/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  InitProductParams,
  initProductParamsBeet,
} from '../types/InitProductParams.js'

/**
 * @category Instructions
 * @category InitProduct
 * @category generated
 */
export type InitProductInstructionArgs = {
  params: InitProductParams
}
/**
 * @category Instructions
 * @category InitProduct
 * @category generated
 */
export const initProductStruct = new beet.BeetArgsStruct<
  InitProductInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', initProductParamsBeet],
  ],
  'InitProductInstructionArgs',
)
/**
 * Accounts required by the _initProduct_ instruction
 *
 * @property [] tokenProgram2022
 * @property [_writable_, **signer**] signer
 * @property [_writable_] marketplace
 * @property [_writable_] product
 * @property [_writable_] productMint
 * @property [] paymentMint
 * @property [_writable_] accessMint (optional)
 * @property [_writable_] accessVault (optional)
 * @category Instructions
 * @category InitProduct
 * @category generated
 */
export type InitProductInstructionAccounts = {
  systemProgram?: web3.PublicKey
  tokenProgram2022: web3.PublicKey
  rent?: web3.PublicKey
  signer: web3.PublicKey
  marketplace: web3.PublicKey
  product: web3.PublicKey
  productMint: web3.PublicKey
  paymentMint: web3.PublicKey
  accessMint?: web3.PublicKey
  accessVault?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initProductInstructionDiscriminator = [
  170, 237, 92, 232, 240, 86, 89, 222,
]

/**
 * Creates a _InitProduct_ instruction.
 *
 * Optional accounts that are not provided will be omitted from the accounts
 * array passed with the instruction.
 * An optional account that is set cannot follow an optional account that is unset.
 * Otherwise an Error is raised.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitProduct
 * @category generated
 */
export function createInitProductInstruction(
  accounts: InitProductInstructionAccounts,
  args: InitProductInstructionArgs,
  programId = new web3.PublicKey('brick5uEiJqSkfuAvMtKmq7kiuEVmbjVMiigyV51GRF'),
) {
  const [data] = initProductStruct.serialize({
    instructionDiscriminator: initProductInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram2022,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.marketplace,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.product,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.productMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.paymentMint,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.accessMint != null) {
    keys.push({
      pubkey: accounts.accessMint,
      isWritable: true,
      isSigner: false,
    })
  }
  if (accounts.accessVault != null) {
    if (accounts.accessMint == null) {
      throw new Error(
        "When providing 'accessVault' then 'accounts.accessMint' need(s) to be provided as well.",
      )
    }
    keys.push({
      pubkey: accounts.accessVault,
      isWritable: true,
      isSigner: false,
    })
  }

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
