/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
import { Key, keyBeet } from '../types/Key.js'

/**
 * Arguments used to create {@link CollectionV1}
 * @category Accounts
 * @category generated
 */
export type CollectionV1Args = {
  key: Key
  updateAuthority: web3.PublicKey
  name: string
  uri: string
  numMinted: number
  currentSize: number
}
/**
 * Holds the data for the {@link CollectionV1} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class CollectionV1 implements CollectionV1Args {
  private constructor(
    readonly key: Key,
    readonly updateAuthority: web3.PublicKey,
    readonly name: string,
    readonly uri: string,
    readonly numMinted: number,
    readonly currentSize: number,
  ) {}

  /**
   * Creates a {@link CollectionV1} instance from the provided args.
   */
  static fromArgs(args: CollectionV1Args) {
    return new CollectionV1(
      args.key,
      args.updateAuthority,
      args.name,
      args.uri,
      args.numMinted,
      args.currentSize,
    )
  }

  /**
   * Deserializes the {@link CollectionV1} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [CollectionV1, number] {
    return CollectionV1.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link CollectionV1} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<CollectionV1> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find CollectionV1 account at ${address}`)
    }
    return CollectionV1.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, collectionV1Beet)
  }

  /**
   * Deserializes the {@link CollectionV1} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [CollectionV1, number] {
    return collectionV1Beet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link CollectionV1} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return collectionV1Beet.serialize(this)
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link CollectionV1} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: CollectionV1Args) {
    const instance = CollectionV1.fromArgs(args)
    return collectionV1Beet.toFixedFromValue(instance).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link CollectionV1} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: CollectionV1Args,
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      CollectionV1.byteSize(args),
      commitment,
    )
  }

  /**
   * Returns a readable version of {@link CollectionV1} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      key: 'Key.' + Key[this.key],
      updateAuthority: this.updateAuthority.toBase58(),
      name: this.name,
      uri: this.uri,
      numMinted: this.numMinted,
      currentSize: this.currentSize,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const collectionV1Beet = new beet.FixableBeetStruct<
  CollectionV1,
  CollectionV1Args
>(
  [
    ['key', keyBeet],
    ['updateAuthority', beetSolana.publicKey],
    ['name', beet.utf8String],
    ['uri', beet.utf8String],
    ['numMinted', beet.u32],
    ['currentSize', beet.u32],
  ],
  CollectionV1.fromArgs,
  'CollectionV1',
)
