/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { Key, keyBeet } from '../types/Key.js'

/**
 * Arguments used to create {@link HashedAssetV1}
 * @category Accounts
 * @category generated
 */
export type HashedAssetV1Args = {
  key: Key
  hash: number[] /* size: 32 */
}
/**
 * Holds the data for the {@link HashedAssetV1} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class HashedAssetV1 implements HashedAssetV1Args {
  private constructor(
    readonly key: Key,
    readonly hash: number[] /* size: 32 */,
  ) {}

  /**
   * Creates a {@link HashedAssetV1} instance from the provided args.
   */
  static fromArgs(args: HashedAssetV1Args) {
    return new HashedAssetV1(args.key, args.hash)
  }

  /**
   * Deserializes the {@link HashedAssetV1} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [HashedAssetV1, number] {
    return HashedAssetV1.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link HashedAssetV1} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<HashedAssetV1> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find HashedAssetV1 account at ${address}`)
    }
    return HashedAssetV1.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, hashedAssetV1Beet)
  }

  /**
   * Deserializes the {@link HashedAssetV1} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [HashedAssetV1, number] {
    return hashedAssetV1Beet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link HashedAssetV1} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return hashedAssetV1Beet.serialize(this)
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link HashedAssetV1}
   */
  static get byteSize() {
    return hashedAssetV1Beet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link HashedAssetV1} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      HashedAssetV1.byteSize,
      commitment,
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link HashedAssetV1} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === HashedAssetV1.byteSize
  }

  /**
   * Returns a readable version of {@link HashedAssetV1} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      key: 'Key.' + Key[this.key],
      hash: this.hash,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const hashedAssetV1Beet = new beet.BeetStruct<
  HashedAssetV1,
  HashedAssetV1Args
>(
  [
    ['key', keyBeet],
    ['hash', beet.uniformFixedSizeArray(beet.u8, 32)],
  ],
  HashedAssetV1.fromArgs,
  'HashedAssetV1',
)
