/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * Arguments used to create {@link Access}
 * @category Accounts
 * @category generated
 */
export type AccessArgs = {
  authority: web3.PublicKey
  marketplace: web3.PublicKey
  bump: number
}

export const accessDiscriminator = [117, 154, 108, 210, 202, 83, 96, 222]
/**
 * Holds the data for the {@link Access} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Access implements AccessArgs {
  private constructor(
    readonly authority: web3.PublicKey,
    readonly marketplace: web3.PublicKey,
    readonly bump: number,
  ) {}

  /**
   * Creates a {@link Access} instance from the provided args.
   */
  static fromArgs(args: AccessArgs) {
    return new Access(args.authority, args.marketplace, args.bump)
  }

  /**
   * Deserializes the {@link Access} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [Access, number] {
    return Access.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Access} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<Access> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Access account at ${address}`)
    }
    return Access.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'brick5uEiJqSkfuAvMtKmq7kiuEVmbjVMiigyV51GRF',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, accessBeet)
  }

  /**
   * Deserializes the {@link Access} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Access, number] {
    return accessBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Access} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return accessBeet.serialize({
      accountDiscriminator: accessDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Access}
   */
  static get byteSize() {
    return accessBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Access} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Access.byteSize,
      commitment,
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Access} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Access.byteSize
  }

  /**
   * Returns a readable version of {@link Access} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      authority: this.authority.toBase58(),
      marketplace: this.marketplace.toBase58(),
      bump: this.bump,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const accessBeet = new beet.BeetStruct<
  Access,
  AccessArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['authority', beetSolana.publicKey],
    ['marketplace', beetSolana.publicKey],
    ['bump', beet.u8],
  ],
  Access.fromArgs,
  'Access',
)
