/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
import { RewardBumps, rewardBumpsBeet } from '../types/RewardBumps.js'

/**
 * Arguments used to create {@link Reward}
 * @category Accounts
 * @category generated
 */
export type RewardArgs = {
  authority: web3.PublicKey
  marketplace: web3.PublicKey
  rewardVaults: web3.PublicKey[]
  bumps: RewardBumps
}

export const rewardDiscriminator = [174, 129, 42, 212, 190, 18, 45, 34]
/**
 * Holds the data for the {@link Reward} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Reward implements RewardArgs {
  private constructor(
    readonly authority: web3.PublicKey,
    readonly marketplace: web3.PublicKey,
    readonly rewardVaults: web3.PublicKey[],
    readonly bumps: RewardBumps,
  ) {}

  /**
   * Creates a {@link Reward} instance from the provided args.
   */
  static fromArgs(args: RewardArgs) {
    return new Reward(
      args.authority,
      args.marketplace,
      args.rewardVaults,
      args.bumps,
    )
  }

  /**
   * Deserializes the {@link Reward} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [Reward, number] {
    return Reward.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Reward} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<Reward> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Reward account at ${address}`)
    }
    return Reward.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'brick5uEiJqSkfuAvMtKmq7kiuEVmbjVMiigyV51GRF',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, rewardBeet)
  }

  /**
   * Deserializes the {@link Reward} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Reward, number] {
    return rewardBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Reward} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return rewardBeet.serialize({
      accountDiscriminator: rewardDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Reward} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: RewardArgs) {
    const instance = Reward.fromArgs(args)
    return rewardBeet.toFixedFromValue({
      accountDiscriminator: rewardDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Reward} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: RewardArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Reward.byteSize(args),
      commitment,
    )
  }

  /**
   * Returns a readable version of {@link Reward} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      authority: this.authority.toBase58(),
      marketplace: this.marketplace.toBase58(),
      rewardVaults: this.rewardVaults,
      bumps: this.bumps,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const rewardBeet = new beet.FixableBeetStruct<
  Reward,
  RewardArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['authority', beetSolana.publicKey],
    ['marketplace', beetSolana.publicKey],
    ['rewardVaults', beet.array(beetSolana.publicKey)],
    ['bumps', rewardBumpsBeet],
  ],
  Reward.fromArgs,
  'Reward',
)
