/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type BoolValueChange = {
  old: boolean
  new: boolean
}

/**
 * @category userTypes
 * @category generated
 */
export const boolValueChangeBeet = new beet.BeetArgsStruct<BoolValueChange>(
  [
    ['old', beet.bool],
    ['new', beet.bool],
  ],
  'BoolValueChange',
)
