/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { Fee, feeBeet } from './Fee.js'
export type ConfigLpParams = {
  minFee: beet.COption<Fee>
  maxFee: beet.COption<Fee>
  liquidityTarget: beet.COption<beet.bignum>
  treasuryCut: beet.COption<Fee>
}

/**
 * @category userTypes
 * @category generated
 */
export const configLpParamsBeet =
  new beet.FixableBeetArgsStruct<ConfigLpParams>(
    [
      ['minFee', beet.coption(feeBeet)],
      ['maxFee', beet.coption(feeBeet)],
      ['liquidityTarget', beet.coption(beet.u64)],
      ['treasuryCut', beet.coption(feeBeet)],
    ],
    'ConfigLpParams',
  )
