/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { FeeCents, feeCentsBeet } from './FeeCents.js'
export type FeeCentsValueChange = {
  old: FeeCents
  new: FeeCents
}

/**
 * @category userTypes
 * @category generated
 */
export const feeCentsValueChangeBeet =
  new beet.BeetArgsStruct<FeeCentsValueChange>(
    [
      ['old', feeCentsBeet],
      ['new', feeCentsBeet],
    ],
    'FeeCentsValueChange',
  )
