/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type U32ValueChange = {
  old: number
  new: number
}

/**
 * @category userTypes
 * @category generated
 */
export const u32ValueChangeBeet = new beet.BeetArgsStruct<U32ValueChange>(
  [
    ['old', beet.u32],
    ['new', beet.u32],
  ],
  'U32ValueChange',
)
