/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type U64ValueChange = {
  old: beet.bignum
  new: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const u64ValueChangeBeet = new beet.BeetArgsStruct<U64ValueChange>(
  [
    ['old', beet.u64],
    ['new', beet.u64],
  ],
  'U64ValueChange',
)
